# title: My Fun Blog
# email: missginski@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   This is a fun blog where I try new things and talk about it.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: missginski
# github_username:  missginski

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed
